#------------------------------------------------------------------------------
# TravisCI configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at:
#
# http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
branches:
    only:
        - develop
        - merge_repos
        - release
    except:
        - /develop-v[0-9]/
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
          env: ZIP_SUFFIX=ubuntu-trusty
          env: TESTS=On
        - os: osx
          osx_image: beta-xcode6.2
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
          env: ZIP_SUFFIX=osx-mavericks
          env: TESTS=On
        - os: osx
          osx_image: xcode7.1
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
          env: ZIP_SUFFIX=osx-yosemite
          env: TESTS=On
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
          env: ZIP_SUFFIX=osx-elcapitan
          env: TESTS=Off
git:
    depth: 2
cache:
    - ccache
    - directories: build
install:
    - ./scripts/install_deps.sh
before_script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$TRAVIS_BUILD_TYPE -DTESTS=$TESTS
    - make -j2
    - ../scripts/release.sh $ZIP_SUFFIX $TESTS
script:
    - cd $TRAVIS_BUILD_DIR/..
    #- git clone https://github.com/ethereum/tests.git
    #- export ETHEREUM_TEST_PATH=$(pwd)/tests/
    #- cd $TRAVIS_BUILD_DIR/build
    #- ./test/libethereum/test/testeth
    #- ./test/libweb3core/test/testweb3core
    #- ./test/webthree/test/testweb3    
deploy:
    provider: releases
    api_key:
        secure: HHcAWFjVNwf8b83KVQnEa172Eo7aur+scVCq4BzgPDXnF+v4GDXT7PAaXyWBwIyrFoIJduPCojsiIBP8QZwtjaKgnywnREjaLc0syTCLSeUHcp/+jPRdickvfgHJWG06sU7ZST8/HnGmoOqV/BUlGhHiqma1oJfGEJ6aaG4oza77ZYAxLPxwq9NOuTHVGJwlphcfeevcU3F0C/mxDEEMEz66lDolp4DCP5L4muHlrOCZ+HSjRwz5/anVNVWNO/nM1I0wmI2TRAS0RPzwClVD8iiGJHhZ/WdgenG4nosBG9UQjd/56LLKI25bIJijz/tpe89pCRUJtMYtcXR5C7w8Is05a1GMedBAiT7Bu35qHbpxJeqcw26DJL4U3+IeHfymXpK/E3RAj16bj+mtxxYSEzaae7obCm1rDA1LnPTI94kAea2ZNOUucDK5FaROX/uBXk422xrQTdJpEpg4TLa7GmQGdtyJC0OnzaOTXWg87lbVMq1PndDLE3STqXT5J/wj/WfUtXlN38x9aX7wwrmyCXY3WJ1zzShAgRO9YjRRosMBkahGDj5l75w9KX8yW3C5txcxjPVGSxQIl+bv9FPrBJmU1WOOPYQlHm92JQJus8BXXQCuhg3mEsZQfmGpgrS82NUB15V1nZB3xCXniKcKnQirzbRXLg8wjlPbT9DKGbc=
    file: $TRAVIS_BUILD_DIR/cpp-ethereum-develop-$ZIP_SUFFIX.zip
    skip_cleanup: true
    on:
        repo: bobsummerwill/cpp-ethereum
        branch: merge_repos
